version: 2
updates:
- package-ecosystem: composer
  directory: "/images/reactphp"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  labels:
  - Dependencies
- package-ecosystem: docker
  directory: "/images/reactphp"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  labels:
  - Dependencies
- package-ecosystem: npm
  directory: "/images/nodejs"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  labels:
  - Dependencies
- package-ecosystem: docker
  directory: "/images/nodejs"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  labels:
  - Dependencies
